joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

###############################################
################ Left Leg #####################
bum_zlj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_zlj
  pid: {p: 10.0, i: 0.0, d: 0.5}

bum_xlj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_xlj
  pid: {p: 10.0, i: 0.0, d: 0.5}

bum_ylj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_ylj
  pid: {p: 10.0, i: 0.0, d: 0.5}

knee_left_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: knee_left
  pid: {p: 10.0, i: 0.0, d: 0.5}

ankle_lj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_lj
  pid: {p: 10.0, i: 0.0, d: 0.5}


foot_lj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: foot_lj
  pid: {p: 10.0, i: 0.0, d: 0.5}
#############################################
############################################




###############################################
################ Right Leg #####################
bum_zrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_zrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

bum_xrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_xrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

bum_yrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: bum_yrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

knee_right_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: knee_right
  pid: {p: 10.0, i: 0.0, d: 0.5}

ankle_rj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: ankle_rj
  pid: {p: 10.0, i: 0.0, d: 0.5}


foot_rj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: foot_rj
  pid: {p: 10.0, i: 0.0, d: 0.5}
#############################################
############################################


###############################################
################ left hand #####################
shoulder_zlj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_zlj
  pid: {p: 10.0, i: 0.0, d: 0.5}

shoulder_xlj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_xlj
  pid: {p: 10.0, i: 0.0, d: 0.5}

shoulder_ylj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_ylj
  pid: {p: 10.0, i: 0.0, d: 0.5}

forearm_ylj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: forearm_ylj
  pid: {p: 10.0, i: 0.0, d: 0.5}

##################################################
##################################################



###############################################
################ left hand #####################
shoulder_zrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_zrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

shoulder_xrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_xrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

shoulder_yrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: shoulder_yrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

forearm_yrj_joint_position_controller:
  type: effort_controllers/JointPositionController
  joint: forearm_yrj
  pid: {p: 10.0, i: 0.0, d: 0.5}

##################################################
##################################################